### ISSUE TITLE
Add new release for the the new package id

### ISSUE THREAD

**Issue by krt16s** [SecUSo/privacy-friendly-dicer#3]
The latest release is still targeting the old package id, it would be good to have a new release (tag and updated versioncode) for the new, hopefull stable id. Package ids should actually never change, since for Android this are now two different applications and there is no way to upgrade older releases to the new one.

**Comment by Yonjuni** [comment]
In which file do I have to change it?

**Comment by Yonjuni** [comment]
Okay, sorry I was a little confused ;) 
I just added a new release. Thanks for the advice regarding the package ID. We had to change it, because we had used a new (common) key to sign our apps for the Google Playstore and were not able to update it without changing the package name. This already caused us a lot of trouble.
